### ISSUE TITLE
Flux on Cray xc40

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#3064]
We have users who want to run OpenMPI on Cray systems at LANL and NERSC. This ticket is opened to track the status of this support. 

Current status:
- @SteVwonder and LANL were able to build flux-core and flux-shed on Trinitite.
-  If you build an MPI with OpenMPI, LANL configuration is such that it adds RPATH to cray PMI library which is not compatible with Flux

**Comment by dongahn** [comment]
From LANL:

>    Yes libpmi.so is rpath'ed in into the executable this is done by the openmpi wrapper. Below I tried to set the LD_PRELOAD to point your libpmi2.so , as it does
have the missing pmi2 symbols , but "alps" sublayer will not initialize within openmpi based on your pmi2 library .
   As a note, i have built up the just released 0.17 of flux-core and 0.9 release of flux-scheduler. and will try them once i can get them pushed to "gadget" .  Will the new version of flux now launch a pmix execuable directly, possibly using the srun provided pmix server ? As this is the other working job launch mechinisim we have on the crays other than the cray pmi2 . If i am not mistaken , openmpi4 is "suppose" to dlopen the library exposed in in the FLUX_PMI_LIBRARY_PATH. I do not believe i have your libraries in my LD_LIBRARY_PATH ( shown below) .  Is there a way to disable the preloading / your flux mini might be doing so it run with its craypmi and pmix libraries intact ? or will the job launch ultimately fail.
 
```console 
mcoyne@nid00027:~> env  | grep LD_LIBRARY
CRAYPAT_LD_LIBRARY_PATH=/opt/cray/pe/gcc-libs:/opt/cray/gcc-libs:/opt/cray/pe/perftools/7.0.6/lib64
LD_LIBRARY_PATH=/usr/projects/consult/mcoyne/craysuse12x/flux-sched/gcc73/0.8.0/lib64:/usr/projects/consult/mcoyne/craysuse12x/python_gcc73_icn/lib:/opt/cray/wlm_detect/1.3.3-6.0.7.1_5.8__g7109084.ari/lib64:/opt/cray/pe/perftools/7.0.6/lib64:/opt/cray/rca/2.2.18-6.0.7.1_5.55__g2aa4f39.ari/lib64:/opt/cray/alps/6.6.43-6.0.7.1_5.54__ga796da32.ari/lib64:/opt/cray/xpmem/2.2.15-6.0.7.1_5.16__g7549d06.ari/lib64:/opt/cray/dmapp/7.1.1-6.0.7.1_6.9__g45d1b37.ari/lib64:/opt/cray/pe/pmi/5.0.14/lib64:/opt/cray/ugni/6.0.14.0-6.0.7.1_3.18__gea11d3d.ari/lib64:/opt/cray/udreg/2.3.2-6.0.7.1_5.18__g5196236.ari/lib64:/opt/cray/pe/libsci/19.02.1/GNU/8.1/x86_64/lib:/opt/cray/pe/mpt/7.7.6/gni/mpich-cray/8.2/lib:/opt/cray/pe/mpt/7.7.6/gni/mpich-gnu/8.2/lib:/usr/projects/consult/mcoyne/craysuse12x/openmpi40/gcc73/4.0.3/lib64:/usr/projects/consult/mcoyne/craysuse12x/library/ucx17_gcc73_icn/1.7.0/lib:/usr/projects/consult/mcoyne/craysuse12x/library/libfabric19_gcc73_icn/1.9.0/lib:/usr/projects/consult/mcoyne/craysuse12x/gcc/gcc73/7.3.1/lib:/usr/projects/consult/mcoyne/craysuse12x/gcc/gcc73/7.3.1/lib64:/usr/projects/consult/mcoyne/craysuse12x/buildtools/lib64:/opt/pmix/gcc4x/3.1.4/lib64:/opt/libevent/gcc4x/2.1.8/lib64:/opt/cray/job/2.2.3-6.0.7.1_5.50__g6c4e934.ari/lib64:/opt/gcc/8.2.0/snos/lib64
CRAY_LD_LIBRARY_PATH=/opt/cray/wlm_detect/1.3.3-6.0.7.1_5.8__g7109084.ari/lib64:/opt/cray/pe/perftools/7.0.6/lib64:/opt/cray/rca/2.2.18-6.0.7.1_5.55__g2aa4f39.ari/lib64:/opt/cray/alps/6.6.43-6.0.7.1_5.54__ga796da32.ari/lib64:/opt/cray/xpmem/2.2.15-6.0.7.1_5.16__g7549d06.ari/lib64:/opt/cray/dmapp/7.1.1-6.0.7.1_6.9__g45d1b37.ari/lib64:/opt/cray/pe/pmi/5.0.14/lib64:/opt/cray/ugni/6.0.14.0-6.0.7.1_3.18__gea11d3d.ari/lib64:/opt/cray/udreg/2.3.2-6.0.7.1_5.18__g5196236.ari/lib64:/opt/cray/pe/libsci/19.02.1/GNU/8.1/x86_64/lib:/opt/cray/pe/mpt/7.7.6/gni/mpich-cray/8.2/lib:/opt/cray/pe/mpt/7.7.6/gni/mpich-gnu/8.2/lib
mcoyne@nid00027:~>
 
 
mcoyne@nid00028:~> readelf -d ./xthi

Dynamic section at offset 0x2d78 contains 34 entries:
<CUT>
 0x000000000000001d (RUNPATH)            Library runpath: [/usr/projects/consult/mcoyne/craysuse12x/library/ucx17_gcc73_icn/1.7.0/lib:/opt/cray/xpmem/default/lib64:/opt/cray/pe/pmi/default/lib64:/opt/cray/alps/default/lib64:/opt/cray/udreg/default/lib64:/opt/cray/wlm_detect/1.3.3-6.0.7.1_5.8__g7109084.ari/lib64:/usr/projects/consult/mcoyne/craysuse12x/openmpi40/gcc73/4.0.3/lib64]

mcoyne@nid00028:~>
 
mcoyne@nid00028:~> flux mini run -N2  -n 2  env  LD_PRELOAD=/usr/projects/consult/mcoyne/craysuse12x/flux-core/gcc73/0.16.0/lib64/flux/libpmi2.so ./xthi
--------------------------------------------------------------------------
The application appears to have been direct launched using "aprun",
but OMPI was not built with ALPS PMI support and therefore cannot
execute. You must build Open MPI using --with-pmi pointing
to the ALPS PMI library location.

Please configure as appropriate and try again.
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nid00029:09876] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
^Cflux-job: one more ctrl-C within 2s to cancel or ctrl-Z to detach
^C70.874s: job.exception type=cancel severity=0 interrupted by ctrl-C
flux-job: task(s) exited with exit code 143
mcoyne@nid00028:~>
```

**Comment by dongahn** [comment]
> Yes libpmi.so is rpath'ed in into the executable this is done by the openmpi wrapper. Below I tried to set the LD_PRELOAD to point your libpmi2.so , as it does
have the missing pmi2 symbols , but "alps" sublayer will not initialize within openmpi based on your pmi2 library .
 
I believe this is one step further! But the environment is such that OpenMPI still detects that this is ALPS system and uses apls underneath and I’d like to find a way to undo this.
 
> Will the new version of flux now launch a pmix execuable directly, possibly using the srun provided pmix server ?
 
No. We don’t support PMIx. However, OpenMPI will bootstrap MPI using PMI when it detects that it is running under Flux.
 
I think the following two concrete next steps will be getting us one more step towards feasibility.  
 
Could you launch OpenMPI under SLURM and see if OpenMPI also uses APLS underneath? If SLURM can do this w/o ALPS, we should do the same with Flux.
 
There are some magic we needed to support SpectrumMPI which is based on OpenMPI. I will find that and send it to you. If we are lucky, that could serve us well in this case too.

**Comment by dongahn** [comment]
Tagging @koning and @ptbremer

**Comment by dongahn** [comment]
@garlick tells me that MPI plugins are now at https://github.com/flux-framework/flux-core/tree/master/src/shell/lua.d

We should set runs with `-o mpi=openmpi` and `-o mpi=spectrum`? I’d like to see what different each makes

```console
:~> flux mini run -N2  -n 2  -o mpi=openmpi env  LD_PRELOAD=/usr/projects/consult/mcoyne/craysuse12x/flux-core/gcc73/0.16.0/lib64/flux/libpmi2.so ./xthi

:~> flux mini run -N2  -n 2  -o mpi=spectrum env  LD_PRELOAD=/usr/projects/consult/mcoyne/craysuse12x/flux-core/gcc73/0.16.0/lib64/flux/libpmi2.so ./xthi
```
My guess is we may want to manually learn the combination envVar to set and unset to make OpenMPI on Cray detect Flux and encapsulate that into our MPI plugin.

**Comment by dongahn** [comment]
From: "Coyne, Michael K":

I did get the version updated current for you flux and its scheduler , this is also with openmpi 4.0.4 .. just in case..  still on the machine gadget..it appears i have a lua module problem i will see if i can fix that . 

mcoyne@nid00028:~> flux mini run -N2  -n 2  -o mpi=openmpi env  LD_PRELOAD=/usr/projects/consult/mcoyne/craysuse12x/flux-core/gcc73/0.17.0/lib64/flux/libpmi2.so ./xthi
./xthi: symbol lookup error: /usr/projects/consult/mcoyne/craysuse12x/openmpi40/gcc73/4.0.4/lib64/libopen-pal.so.40: undefined symbol: PMI_Get_version_info
./xthi: symbol lookup error: /usr/projects/consult/mcoyne/craysuse12x/openmpi40/gcc73/4.0.4/lib64/libopen-pal.so.40: undefined symbol: PMI_Get_version_info
flux-job: task(s) exited with exit code 127
mcoyne@nid00028:~> ls /usr/projects/consult/mcoyne/craysuse12x/flux-core/gcc73/0.17.0/lib64/flux/libpmi2.so
/usr/projects/consult/mcoyne/craysuse12x/flux-core/gcc73/0.17.0/lib64/flux/libpmi2.so
mcoyne@nid00028:~> flux mini run -N2  -n 2  -o mpi=spectrum  env  LD_PRELOAD=/usr/projects/consult/mcoyne/craysuse12x/flux-core/gcc73/0.17.0/lib64/flux/libpmi2.so ./xthi
0.107s: flux-shell[0]: ERROR: ...flux-core/gcc73/0.17.0/etc/flux/shell/lua.d/spectrum.lua:15: module 'posix' not found:
        no field package.preload['posix']
        no file '/usr/projects/consult/mcoyne/craysuse12x/flux-core/gcc73/0.17.0/share/lua/5.2/posix.lua'
        no file '/usr/projects/consult/mcoyne/craysuse12x/flux-sched/gcc73/0.9.0/share/lua/5.1:/usr/projects/consult/mcoyne/craysuse12x/flux-sched/gcc73/0.9.0/rd1:/usr/projects/consult/mcoyne/craysuse12x/flux-core/gcc73/0.17.0/share/lua/5.2'
        no file '/usr/share/lua/5.2/posix.lua'
        no file '/usr/share/lua/5.2/posix/init.lua'
        no file '/usr/lib64/lua/5.2/posix.lua'
        no file '/usr/lib64/lua/5.2/posix/init.lua'
        no file './posix.lua'
        no file '/usr/projects/consult/mcoyne/craysuse12x/flux-core/gcc73/0.17.0/lib/lua/5.2/posix.so'
        no file '/usr/projects/consult/mcoyne/craysuse12x/flux-sched/gcc73/0.9.0/share/lua/5.1:/usr/projects/consult/mcoyne/craysuse12x/flux-sched/gcc73/0.9.0/rd1:/usr/projects/consult/mcoyne/craysuse12x/flux-core/gcc73/0.17.0/lib/lua/5.2'
        no file '/usr/lib64/lua/5.2/posix.so'
        no file '/usr/lib64/lua/5.2/loadall.so'
        no file './posix.so'
0.108s: flux-shell[0]: ERROR: ...suse12x/flux-core/gcc73/0.17.0/etc/flux/shell/initrc.lua:8: source /usr/projects/consult/mcoyne/craysuse12x/flux-core/gcc73/0.17.0/etc/flux/shell/lua.d/spectrum.lua failed
0.108s: flux-shell[0]: FATAL: loading rc file /usr/projects/consult/mcoyne/craysuse12x/flux-core/gcc73/0.17.0/etc/flux/shell/initrc.lua
0.109s: job.exception type=exec severity=0 loading rc file /usr/projects/consult/mcoyne/craysuse12x/flux-core/gcc73/0.17.0/etc/flux/shell/initrc.lua
flux-job: task(s) exited with exit code 1
mcoyne@nid00028:~>

**Comment by dongahn** [comment]
Looks like Lua dependency has not been installed. @Herbein, Stephen: Spack probably doesn’t capture this?
 
Mike: yeah it seems best to satisfy them manually at this point..

**Comment by SteVwonder** [comment]
> Looks like Lua dependency has not been installed. 

Agreed.  The lua-posix module needs to be installed, but this doesn't look like a spack installation.  It looks like a manual install.  If it is a spack installation, then the lua-posix package might not have been loaded.  `spack load -r flux-sched` should fix that (note the `-r` to recursively load dependencies).

**Comment by dongahn** [comment]
i "manually" put lua.posix somewhere it could be found   
btw.. this is not being built with spack it all being done from rpms, same setup i use
to build my production slurm packages.

mcoyne@nid00028:~> flux mini run -N2  -n 2  -o mpi=spectrum  env  LD_PRELOAD=/usr/projects/consult/mcoyne/craysuse12x/flux-core/gcc73/0.17.0/lib64/flux/libpmi2.so ./xthi
ERROR: ld.so: object '/opt/ibm/spectrum_mpi/lib/libpami_cudahook.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/opt/ibm/spectrum_mpi/lib/libpami_cudahook.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
./xthi: symbol lookup error: /usr/projects/consult/mcoyne/craysuse12x/openmpi40/gcc73/4.0.4/lib64/libopen-pal.so.40: undefined symbol: PMI_Get_version_info
./xthi: symbol lookup error: /usr/projects/consult/mcoyne/craysuse12x/openmpi40/gcc73/4.0.4/lib64/libopen-pal.so.40: undefined symbol: PMI_Get_version_info
flux-job: task(s) exited with exit code 127

**Comment by dongahn** [comment]
./xthi is still getting to the vendor specific logic which should be avoided. Two things.

1)	Can we run ompi_info to see if flux support is even compiled into /usr/projects/consult/mcoyne/craysuse12x/openmpi40?
https://stackoverflow.com/questions/36635061/how-to-check-which-mca-parameters-are-used-in-openmpi

2)	If it is, we probably need to find a magic environmental variables (maybe setting some envVariables and unsetting some envVariables) to make OpenMPI exercise that. 

Mike: are you the in-house OpenMPI expert at LANL or is there someone else who can consult us with?

**Comment by SteVwonder** [comment]
> If it is, we probably need to find a magic environmental variables (maybe setting some envVariables and unsetting some envVariables) to make OpenMPI exercise that.

I haven't tried it yet, but I believe to have OpenMPI use the Flux "pmix" plugin (it isn't really pmix, it is the bootstrap method) rather than the Cray one, you can set `OMPI_MCA_pmix=flux`.  Alternatively, you can disallow cray with `OMPI_MCA_pmix=^cray`.  I'm not sure how to compose the two (or if composing them is really necessary).

**Comment by dongahn** [comment]
MCA schizo: flux (MCA v2.1.0, API v1.0.0, Component v4.0.4)
              MCA schizo: ompi (MCA v2.1.0, API v1.0.0, Component v4.0.4)
              MCA schizo: orte (MCA v2.1.0, API v1.0.0, Component v4.0.4)
              MCA schizo: alps (MCA v2.1.0, API v1.0.0, Component v4.0.4)
              MCA schizo: slurm (MCA v2.1.0, API v1.0.0, Component v4.0.4)
 
No i am not, you would want to chat with Howard Pritchard or Dave Shrader  as well as jen they are who i turn to for support at lanl.

**Comment by dongahn** [comment]
Do you also see MCA pmix? If not, can we compile that in?
 
lassen708{dahn}22: ompi_info | grep flux
                MCA pmix: flux (MCA v2.1.0, API v2.0.0, Component v10.3.0)
              MCA schizo: flux (MCA v2.1.0, API v1.0.0, Component v10.3.0)

**Comment by dongahn** [comment]
From Mike Coyne:

                MCA pmix: isolated (MCA v2.1.0, API v2.0.0, Component v4.0.4)
                MCA pmix: cray (MCA v2.1.0, API v2.0.0, Component v4.0.4)
                MCA pmix: pmix3x (MCA v2.1.0, API v2.0.0, Component v4.0.4)

           MCA pmix base: ---------------------------------------------------
           MCA pmix base: parameter "pmix" (current value: "", data source: default, level: 2 user/detail, type: string)
                          Default selection set of components for the pmix framework (<none> means use all components that can be found)
           MCA pmix base: ---------------------------------------------------
           MCA pmix base: parameter "pmix_base_verbose" (current value: "error", data source: default, level: 8 dev/detail, type: int)
                          Verbosity level for the pmix framework (default: 0)
                          Valid values: -1:"none", 0:"error", 10:"component", 20:"warn", 40:"info", 60:"trace", 80:"debug", 100:"max", 0 - 100
           MCA pmix base: parameter "pmix_base_async_modex" (current value: "false", data source: default, level: 9 dev/all, type: bool)
                          Use asynchronous modex mode
                          Valid values: 0: f|false|disabled|no|n, 1: t|true|enabled|yes|y
           MCA pmix base: parameter "pmix_base_collect_data" (current value: "true", data source: default, level: 9 dev/all, type: bool)
                          Collect all data during modex
                          Valid values: 0: f|false|disabled|no|n, 1: t|true|enabled|yes|y
           MCA pmix base: parameter "pmix_base_exchange_timeout" (current value: "-1", data source: default, level: 3 user/all, type: int)
                          Time (in seconds) to wait for a data exchange to complete
         MCA pmix pmix3x: ---------------------------------------------------
         MCA pmix pmix3x: parameter "pmix_pmix3x_silence_warning" (current value: "false", data source: default, level: 4 tuner/basic, type: bool)
                          Silence warning about PMIX_INSTALL_PREFIX
                          Valid values: 0: f|false|disabled|no|n, 1: t|true|enabled|yes|y
         MCA pmix pmix3x: parameter "pmix_pmix3x_library_version" (current value: "PMIx library version 3.1.5 (embedded in Open MPI)", data source: default, level: 4 tuner/basic, type: string)
                          Version of the underlying PMIx library

here are some of the pmix options in the new openmpi 4.0.4 
one thing of note, symbol that showed up as missing changed it is now
PMI_Get_version_info
it was one of the PMI2  symbols .. i am not sure where it gets resolved at as the craylib pmi does not have it there 


mcoyne@nid00028:~> nm $PMI_LIBRARY | grep PMI_Get
0000000000001d47 T PMI_Get_appnum
0000000000002336 T PMI_Get_clique_ranks
0000000000002235 T PMI_Get_clique_size
0000000000001ec7 T PMI_Get_id
0000000000002021 T PMI_Get_id_length_max
0000000000001f74 T PMI_Get_kvs_domain_id
0000000000004c55 T PMI_Get_options
0000000000001c5f T PMI_Get_rank
0000000000001beb T PMI_Get_size
0000000000001cd3 T PMI_Get_universe_size

i will poke around and see if i can figure out where it is coming from, but also of note your libpmi.so now has some of the PMI2_xxx symbols in it.

Mike

**Comment by dongahn** [comment]
My guess is OpenMPI current uses under Flux:
                MCA pmix: cray (MCA v2.1.0, API v2.0.0, Component v4.0.4)
 
and hit this problem down in the Cray specific library.
 
When it should use:
                MCA pmix: flux
 
I don’t see that MCA module from your output. So I think OpenMPI needs to be reconfigured to compile that in.
 
BTW, W/ NERSC, we are also pursuing to use an MPICH variant instead.

**Comment by dongahn** [comment]
FYI -- @SteVwonder logged onto Cory and try `mpich/3.3.2` with the latest Flux versions. If this comes to fruition, @koning and @ptbremer should immediately rebuild their COVID modeling app with MPICH to use Flux.

**Comment by dongahn** [comment]
From @SteVwonder:

On Cori, it does appear that Flux can successfully bootstrap MPI binaries built with the mpich/3.3.1-debug module. 
 
$ salloc --qos=interactive -C haswell --time=60 --nodes=2
$ PMI_LIBRARY=/usr/lib64/slurmpmi/libpmi.so srun -N2 -n2 --pty flux start
$ flux hwloc info
2 Machines, 64 Cores, 128 PUs
$ flux mini run -N2 -n64 ./mpi-hello-mpich-3.3.1-debug.exe
Hello World from Node 30
Hello World from Node 26
Hello World from Node 19
Hello World from Node 4
<snip>
 
I was previously fearful that the per-node limitations that Cray and Slurm are beholden to by the Aries network would cause issues if Flux tried to launch lots of MPI runs on the same node.  After testing, it appears that isn’t the case with a non-cray mpich (this is just a simple hello world example, so a full simulation may be different):

$ for x in {1..64}; do flux mini submit -N1 -n2 ./mpi-hello-mpich-3.3.1-debug-sleep.exe 120; done
$ flux jobs -a
             JOBID USER     NAME       STATUS NTASKS NNODES  RUNTIME RANKS
    23692885098496 herbein1 mpi-hello-      R      2      1    11.7s 1
    23681963130880 herbein1 mpi-hello-      R      2      1   12.36s 1
    23671393484800 herbein1 mpi-hello-      R      2      1   13.08s 1
    23660656066560 herbein1 mpi-hello-      R      2      1   13.75s 1
<snip>
    23340429344768 herbein1 mpi-hello-     CD      2      1   2.007m 1
    23328618184704 herbein1 mpi-hello-     CD      2      1   2.008m 1
    23317075460096 herbein1 mpi-hello-     CD      2      1   2.007m 1
    23305314631680 herbein1 mpi-hello-     CD      2      1   2.007m 1
 
There are definitely some pain points when using anything Spack-built (conflicts with lua, openssl, ncurses libraries). The currently Spack workflow that I found to produce the fewest warnings:

$ spack load flux-sched@master arch=cray-sles15-x86_64 ^lua@5.3.4^readline@7.0^ncurses@6.1^openssl@1.1.0i
$ spack unload ncurses
$ export LUA_PATH="$LUA_PATH;/usr/share/lua/5.3/?.lua; /usr/lib64/lua/5.3/?.lua; /usr/lib64/lua/5.3/?/init.lua; /usr/share/lua/5.3/?/init.lua"
$ export LUA_CPATH=” $LUA_CPATH;/usr/lib64/lua/5.3/?.so”

If we can get Flux’s dependencies installed at the system-level with the system package manager/RPMs, then the experience will be much smoother.
 
I attempted to compile the mpi-hello-world example with the mpich/3.3.2 module loaded, but I got compiler errors related to nvml (see below).  I’d be happy to give that another try if someone has any suggested changes.  I suspect a spack-built mpich could also work.

herbein1@cori09:~/mpi-hello> module load mpich/3.3.2
herbein1@cori09:~/mpi-hello> which mpicc
/usr/common/software/mpich/3.3.2/cce/9.1.0/cgpu/bin/mpicc
herbein1@cori09:~/mpi-hello> mpicc mpi-hello.c -o mpi-hello-mpich-3.3.2.exe
No supported cpu target is set, CRAY_CPU_TARGET=x86-64 will be used.
Load a valid targeting module or set CRAY_CPU_TARGET
mpi-hello.c:5:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
main(int argc, char **argv)
^
1 warning generated.
/opt/cray/pe/cce/9.1.0/binutils/x86_64/x86_64-pc-linux-gnu/bin/ld.gold: error: cannot find -lnvidia-ml
/usr/common/software/mpich/3.3.2/cce/9.1.0/cgpu/lib/libmpi.a(topology-nvml.o):topology-nvml.c:function hwloc_nvml_discover: error: undefined reference to 'nvmlInit_v2'
/usr/common/software/mpich/3.3.2/cce/9.1.0/cgpu/lib/libmpi.a(topology-nvml.o):topology-nvml.c:function hwloc_nvml_discover: error: undefined reference to 'nvmlDeviceGetCount_v2'
/usr/common/software/mpich/3.3.2/cce/9.1.0/cgpu/lib/libmpi.a(topology-nvml.o):topology-nvml.c:function hwloc_nvml_discover: error: undefined reference to 'nvmlDeviceGetHandleByIndex_v2'
/usr/common/software/mpich/3.3.2/cce/9.1.0/cgpu/lib/libmpi.a(topology-nvml.o):topology-nvml.c:function hwloc_nvml_discover: error: undefined reference to 'nvmlDeviceGetName'
/usr/common/software/mpich/3.3.2/cce/9.1.0/cgpu/lib/libmpi.a(topology-nvml.o):topology-nvml.c:function hwloc_nvml_discover: error: undefined reference to 'nvmlDeviceGetSerial'
/usr/common/software/mpich/3.3.2/cce/9.1.0/cgpu/lib/libmpi.a(topology-nvml.o):topology-nvml.c:function hwloc_nvml_discover: error: undefined reference to 'nvmlDeviceGetUUID'
/usr/common/software/mpich/3.3.2/cce/9.1.0/cgpu/lib/libmpi.a(topology-nvml.o):topology-nvml.c:function hwloc_nvml_discover: error: undefined reference to 'nvmlDeviceGetPciInfo_v3'
/usr/common/software/mpich/3.3.2/cce/9.1.0/cgpu/lib/libmpi.a(topology-nvml.o):topology-nvml.c:function hwloc_nvml_discover: error: undefined reference to 'nvmlDeviceGetMaxPcieLinkWidth'
/usr/common/software/mpich/3.3.2/cce/9.1.0/cgpu/lib/libmpi.a(topology-nvml.o):topology-nvml.c:function hwloc_nvml_discover: error: undefined reference to 'nvmlDeviceGetMaxPcieLinkGeneration'
/usr/common/software/mpich/3.3.2/cce/9.1.0/cgpu/lib/libmpi.a(topology-nvml.o):topology-nvml.c:function hwloc_nvml_discover: error: undefined reference to 'nvmlShutdown'
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dongahn** [comment]
Tagging @Jennfshr from LANL.

**Comment by dongahn** [comment]
From Brandon from NERSC:

> There is unfortunately a namespace collision on Cori at the moment. That mpich module was built with Cori GPU (an 18 node infiniband machine with GPUs run as separate Slurm cluster "escori") See http://docs-dev.nersc.gov.

> I think it is very close to a stock build but with some CUDA flags potentially turned on due to how it was configured which may explain why it worked but with warnings.

> If needed we can stand up another install of MPICH, this time targeted at XC.

**Comment by dongahn** [comment]
A few suggested steps:

- Joe and Timo to rebuild the simulation using mpich/3.3.1-debug and let us know whether you can successfully build your app?
- Brandon: to either put our flux installation by himself or let @SteVwonder know where to put it so that Joe and Timo (or other users) can access it on Cory?
 
If we are successful with 1) and 2), this would be our feasibility that this team can make their end of the week target on Cory.
 
If 1) is successful,

- This team will need another “optimized” mpich build (with no GPU) built for Cory for their production run. Brandon plans to work on it.
- It doesn’t have to be right away, but can Flux’s dependencies are installed using RPM so that Flux deployment can go smoother.

**Comment by dongahn** [comment]
Tagging @sheepherder82 from LANL.

**Comment by brandongc** [comment]
I'm working through a few of the details to get `/global/common/software/flux` setup as location for the install. For the "optimized" MPICH build will Intel MPI work? (`module avail impi`)

**Comment by SteVwonder** [comment]
> For the "optimized" MPICH build will Intel MPI work? (module avail impi)

It appears that it does work, although there are some ominous warnings:

```
herbein1@nid00117:/global/u2/h/herbein1/mpi-hello> flux mini run -N2 -n4 ./mpi-hello-intelmpi-2019.6.166.exe
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Hello World from rank 1
Hello World from rank 0
Hello World from rank 3
Hello World from rank 2
```

If you are only running on a single node, you can force the shared memory "fabric" and then those warnings go away:

```
herbein1@nid00117:/global/u2/h/herbein1/mpi-hello> I_MPI_FABRICS=shm flux mini run -N1 -n2 ./mpi-hello-intelmpi-2019.6.166.exe
Hello World from rank 1
Hello World from rank 0
```

**Comment by dongahn** [comment]
@SteVwonder: do you get a similar error if you run an app compiled with mpich-debug across multiple nodes? If not, it seems the plain mpich configured exactly same as the mpich-debug except for "debugging compilation flags" would be better.  My guess is soon Flux would be needed by not only this team but also other teams on CORI, which may require multi-node MPI jobs...

@brandongc: If mpich-debug produces a better result, can we install mpich optimized instead with the same configuration (to be a bit more future proof)?

**Comment by dongahn** [comment]
From @sheepherder82:

I tried to rebuild this version of open mpi forcing it to directly link to the flux pmi libraries instead of the default dynamic dlopen from and enviornment variable if present.  But it could not resolve symbols , because of it expecting craypmi .. So as a test i built it wih flux  but with out cray mpi .. see cut and paste from my spec file. This did not end well, see the error message below . 
 
It also appears we will be loosing the machine i have been testing on , gadget today or tommorow as it will be upgraded to cle7up2 .We will have to test on trinitite it would appear untill it gets updated.
MIke 

```console 
mcoyne@nid00027:~> flux mini run -N2 -n2 env LD_PRELOAD=/usr/projects/consult/mcoyne/craysuse12x/flux-core/gcc73/0.17.0/lib64/flux/libpmi.so ./xthi
--------------------------------------------------------------------------
A requested component was not found, or was unable to be opened.  This
means that this component is either not installed or is unable to be
used on your system (e.g., sometimes this means that shared libraries
that the component requires are unable to be found/loaded).  Note that
Open MPI stopped checking at the first component that it did not find.

Host:      nid00027
Framework: pmix
Component: cray
--------------------------------------------------------------------------
[nid00027:28111] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file ess_pmi_module.c at line 131
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):
```

**Comment by dongahn** [comment]
@sheepherder82: could you run `ompi_info` again on the newly built OpenMPI and grep for `flux`?  Does it contain `MCA pmix: flux ...` now ?

**Comment by dongahn** [comment]
@sheepherder82: If you build contains that MCA module, it would be good to try @SteVwonder's suggestion at https://github.com/flux-framework/flux-core/issues/3064#issuecomment-662717004.

**Comment by dongahn** [comment]
@sheepherder82: if you are willing to build mpich-based MPI as an alternative as well, you could use the same recipe the @brandongc is working on at NERSC. Please see the comment at https://github.com/flux-framework/flux-core/issues/3064#issuecomment-663298933.

**Comment by dongahn** [comment]
@sheepherder82:

By the way, the following error message does seem to indicate, the OpenMPI is still trying to pick up `OMPI_MCA_pmix=cray`, which needs to be stripped away from the environment variable or similar?

```
Note that
Open MPI stopped checking at the first component that it did not find.

Host:      nid00027
Framework: pmix
Component: cray
```

**Comment by SteVwonder** [comment]
> do you get a similar error if you run an app compiled with mpich-debug across multiple nodes?

I do not. The MPICH debug MPI runs cleanly.

**Comment by SteVwonder** [comment]
Thanks @brandongc for creating a software space at NERSC for Flux.  I just finished an install with Flux on Cori.  Because it is a spack install, there are some weird incompatibilities with the existing system software (specifically ncurses, openssl, readline).  I also didn't want to lock users into using our spack-installed python.  So the workaround for both of these is the following:

```
salloc --qos=interactive -C haswell --time=60 --nodes=2
srun --pty -N2 -n2 /global/common/software/flux/sles15_x86_64/master-2020-07-23/bin/boot-flux.sh
flux mini run -N2 -n32 ./mpi-hello-mpich-3.3.1-debug.exe
Hello World from Node 14
Hello World from Node 13
Hello World from Node 11
Hello World from Node 9
Hello World from Node 7
Hello World from Node 28
<snip>
```

If it is a non-interactive session, you can drop the `--pty` argument to `srun` and add args to the boot script:
```
srun -N2 -n2 /global/common/software/flux/sles15_x86_64/master-2020-07-23/bin/boot-flux.sh $HOME/my-init-prog.sh
```

---

To do a more native compile/install, it would be great if we could get the following packages installed via `zypper`:
```
zeromq-devel
yaml-cpp-devel
libsodium-devel
libboost_{headers,regex,filesystem,system,graph}1_66_0-devel
```

**Comment by sheepherder82** [comment]
compiling openmpi 4.0.4 disableing cray mpi and using staticaly linked flux pmi.     

            MCA pmix: flux (MCA v2.1.0, API v2.0.0, Component v4.0.4)
              MCA schizo: flux (MCA v2.1.0, API v1.0.0, Component v4.0.4)
            MCA pmix flux: ---------------------------------------------------
           MCA pmix flux: parameter "pmix_flux_priority" (current value: "20", data source: default, level: 9 dev/all, type: int)
                          Priority of the pmix flux component (default: 20)

below is the full output  , not the cpu-affinity and gpu-affinity options to get flux  to work on trinitite

mcoyne@nid00105:~> srun -N2 -n2 --pty flux start
flux-broker: dlopen /opt/slurm/lib64/slurmpmi/libpmi.so
flux-broker: using dlopen
mcoyne@nid00105:~> flux mini run -o cpu-affinity="off" -o gpu-affinity="off" -N1 -n1 ./xthi 
--------------------------------------------------------------------------
A requested component was not found, or was unable to be opened.  This
means that this component is either not installed or is unable to be
used on your system (e.g., sometimes this means that shared libraries
that the component requires are unable to be found/loaded).  Note that
Open MPI stopped checking at the first component that it did not find.

Host:      nid00105
Framework: pmix
Component: cray
--------------------------------------------------------------------------
[nid00105:28319] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file ess_pmi_module.c at line 131
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  pmix init failed
  --> Returned value Not found (-13) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_ess_init failed
  --> Returned value Not found (-13) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Not found" (-13) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nid00105:28319] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
flux-job: task(s) exited with exit code 1

**Comment by hppritcha** [comment]
It looks like the open mpi schizo scheme is getting confused.  investigating...

**Comment by hppritcha** [comment]
If I set
export OMPI_MCA_schizo=flux
then I get into flux_init and it looks like the flux PMI_Init fails:
```
hpp@nid00105:/XXXXX/ompi/examples> (v4.0.x *)flux mini run -o cpu-affinity="off" -o gpu-affinity="off" -n 1 ./hello_c
I see OMPI_MCA_pmix = (null)
about to open the opal_pmix_base_framework -  (null)
about to call opal_pmix.init
inside flux_init!!!!!!
[nid00105:45578] PMI_Init [pmix_flux.c:387:flux_init]: Operation failed
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  pmix init failed
  --> Returned value Error (-1) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_ess_init failed
  --> Returned value Error (-1) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Error" (-1) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nid00105:45578] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
flux-job: task(s) exited with exit code 1

**Comment by dongahn** [comment]
@hppritcha and @sheepherder82: `OMPI_MCA_pmix=flux` and `OMPI_MCA_pmix=^cray`

BTW, there is a bug in some versions of OpenMPI w/ respect to this: https://github.com/open-mpi/ompi/issues/6730. So we need to make sure we use an OpenMPI version that fixed this bug or a version that this bug wasn't introduced. 

My guess is Cray environment would set other OMPI environment(s) that can confuser flux-openmpi interaction. We may need to play some more games to see if there are other variables.

If we find a magic formula, we can codify that login into our mpi shell plugin.

**Comment by hppritcha** [comment]
okay, fixed my FLUX_PMI_LIBRARY_PATH and it works now:
```
hpp@nid00105:/XXXXX/ompi/examples> (v4.0.x *)flux mini run -o cpu-affinity="off" -o gpu-affinity="off" -n 4 ./hello_c
inside flux_init!!!!!!
inside flux_init!!!!!!
inside flux_init!!!!!!
inside flux_init!!!!!!
Hello, world, I am 3 of 4, (Open MPI v4.0.5rc1, package: Open MPI hpp@tt-fey1 Distribution, ident: 4.0.5rc1, repo rev: v4.0.5rc1-8-g05745e2f, Unreleased developer copy, 140)
Hello, world, I am 0 of 4, (Open MPI v4.0.5rc1, package: Open MPI hpp@tt-fey1 Distribution, ident: 4.0.5rc1, repo rev: v4.0.5rc1-8-g05745e2f, Unreleased developer copy, 140)
Hello, world, I am 1 of 4, (Open MPI v4.0.5rc1, package: Open MPI hpp@tt-fey1 Distribution, ident: 4.0.5rc1, repo rev: v4.0.5rc1-8-g05745e2f, Unreleased developer copy, 140)
Hello, world, I am 2 of 4, (Open MPI v4.0.5rc1, package: Open MPI hpp@tt-fey1 Distribution, ident: 4.0.5rc1, repo rev: v4.0.5rc1-8-g05745e2f, Unreleased developer copy, 140)
```
Looks like setting the OMPI_MCA_schizo env. variable to flux should help you get further.
Also, sorry to disappoint, but you're not going to be able to use the ugni BTL using the flux PMI and flux launcher.
You'll need to add code similar to that in the OMPI odls/alps to flux PMI if you want to use ugni BTL with flux.  See ```orte_odls_alps_get_rdma_creds``` in the alps component of the odls framework.

**Comment by dongahn** [comment]
This is great news @hppritcha and @sheepherder82!

Could you do our community a bit favor and post your recipe as to how to do this (step by step -- including how you configured OpenMPI and what version) so that other sites hosting Cray machine can replicate your success. Most importantly, this may  be needed by NERSC (@brandongc), if we want OpenMPI to be available for our COVID19 modeling calculation on CORI.

Once this recipe is posted here, I will make sure we will put that into our high level doc in parallel to "how to use Flux on CORAL": https://flux-framework.readthedocs.io/en/latest/coral.html

At some point, doing some performance benchmarking comparing OpenMPI and CrayMPI on Cray machines would also be interesting. But this is for long term. 

Tagging @koning and @ptbremer once again so that they know they may have two MPI choices on Cray machines. 

This is a big advancement. Congratulations and Thanks everyone!

**Comment by dongahn** [comment]
@hppritcha: sorry -- I think I missed one important point though:

> Also, sorry to disappoint, but you're not going to be able to use the ugni BTL using the flux PMI and flux launcher.
You'll need to add code similar to that in the OMPI odls/alps to flux PMI if you want to use ugni BTL with flux. See orte_odls_alps_get_rdma_creds in the alps component of the odls framework.

Hmmm so we need a modification to Flux proper to make this happen? Presumably, you didn't make this change... How did you get the MPI job bootstrapped in `MPI_Init` then?

```
hpp@nid00105:/XXXXX/ompi/examples> (v4.0.x *)flux mini run -o cpu-affinity="off" -o gpu-affinity="off" -n 4 ./hello_c
inside flux_init!!!!!!
inside flux_init!!!!!!
inside flux_init!!!!!!
inside flux_init!!!!!!
Hello, world, I am 3 of 4, (Open MPI v4.0.5rc1, package: Open MPI hpp@tt-fey1 Distribution, ident: 4.0.5rc1, repo rev: v4.0.5rc1-8-g05745e2f, Unreleased developer copy, 140)
Hello, world, I am 0 of 4, (Open MPI v4.0.5rc1, package: Open MPI hpp@tt-fey1 Distribution, ident: 4.0.5rc1, repo rev: v4.0.5rc1-8-g05745e2f, Unreleased developer copy, 140)
Hello, world, I am 1 of 4, (Open MPI v4.0.5rc1, package: Open MPI hpp@tt-fey1 Distribution, ident: 4.0.5rc1, repo rev: v4.0.5rc1-8-g05745e2f, Unreleased developer copy, 140)
Hello, world, I am 2 of 4, (Open MPI v4.0.5rc1, package: Open MPI hpp@tt-fey1 Distribution, ident: 4.0.5rc1, repo rev: v4.0.5rc1-8-g05745e2f, Unreleased developer copy, 140)
```

**Comment by sheepherder82** [comment]
Dong, can you could let me know when you get a patch  to apply to my test flux install on trinititie 
Refering to  @hppritcha  note.. 
```
Also, sorry to disappoint, but you're not going to be able to use the ugni BTL using the flux PMI and flux launcher.
You'll need to add code similar to that in the OMPI odls/alps to flux PMI if you want to use ugni BTL with flux. See orte_odls_alps_get_rdma_creds in the alps component of the odls framework.
```
this will be necessary for meaning full usage on the machine. 
Mike

**Comment by dongahn** [comment]
@sheepherder82: Sounds reasonable. 

> this will be necessary for meaning full usage on the machine. probably on cory as well

So could either you or @hppritcha elaborate the limitations of @hppritcha's solution at https://github.com/flux-framework/flux-core/issues/3064#issuecomment-663637322?

**Comment by sheepherder82** [comment]
In my limited understanding, crays fabric is accessed by their ugni libraries, on a cray you have to gain access to the fabric with a security token to make it accessible,  this is something that is happening in concert with craypmi.  I believe howard built his openmpi w/out ugni  and would only be able to access via tcp/ip connections to other nodes, which is still over the fabric.  As for my self i built my test openmpi's up with both ugni  , and ucx  which uses the ugni  libraries , they of course do no run . Howard can explain better .

**Comment by dongahn** [comment]
@sheepherder82: thank you for the explanation. I think Howard's solution would work for the current use cases as jobs running with Flux are expected to small scale (single node or a few nodes). It should still be worthwhile documenting that work around if you guys are willing.

We can then look at the real solution -- but this may take some time due to our other priorities.

**Comment by hppritcha** [comment]
@sheepherder82  @dongahn you'll want to take the code in OMPI's orte_odls_alps_get_rdma_creds and paste it into either the flux daemon code or into the flux PMI code.  It queries apshepherd or slurmstepd for the rdma credentials, then sets PMI environment variables that the uGNI BTL can pick up.  the process doing the quering doesn't have to be a direct child of apshepherd/slurmstepd as long as there's no fork/exec in the tree that closes all pipes back up to apshepherd/slurmstepd

**Comment by garlick** [comment]
@hppritcha - thanks for the code citation.  This needs to get done in Flux at some point.  Pondering it a bit, here's a question:

From slurm/alps's point of view, Flux is just another parallel program, so it's issued (I guess?) one credential, or a matched set of them for its lifetime, which might be useful if Flux itself wanted to use the interconnect for it's own message passing.  But Flux wants to launch a bunch more parallel programs (some running concurrently) using the resources allocated to it.  If it's only been allocated the one credential, can it launch more than one job that uses the interconnect?

It seems like we are going to need some way to generate/allocate more of them?

**Comment by SteVwonder** [comment]
>  If it's only been allocated the one credential, can it launch more than one job that uses the interconnect?

As a related question, if we use the uGNI BTL, would that subject us to the jobs per node limitations of the Cray network that Slurm enforces? [[1]](https://slurm.schedmd.com/SUG14/cray_native.pdf)  If so, we may want to make that a configuration option so that HTC and MTC users can launch many more MPI jobs per node than just 4.
