### ISSUE TITLE
Spack update?

### ISSUE THREAD

**Issue by andre-merzky** [flux-framework/flux-core#6738]
Would it be possible to update the [spack package](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/flux-core/package.py) ?  The current last version supported seems to be 0.42 which, for example, does not yet include the nice `JournalConsumer` :-)

Best, Andre.

**Comment by grondo** [comment]
I think we're waiting on https://github.com/spack/spack/pull/49656 to be merged. I'll bump that PR to see what it is waiting on .

**Comment by andre-merzky** [comment]
Thanks for getting https://github.com/spack/spack/pull/49656 merged!  My local spack updates for versions `0.73.0`, `0.72.0`, `0.71.0`, `0.70.0`, `0.69.0` and `0.68.0` seems to work (for my tests at least) - do you want me to open a spack package PR with those updates?  It basically just this:

```diff
$ git diff
diff --git i/var/spack/repos/builtin/packages/flux-core/package.py w/var/spack/repos/builtin/packages/flux-core/package.py
index e5d733c4bf..216284ab24 100644
--- i/var/spack/repos/builtin/packages/flux-core/package.py
+++ w/var/spack/repos/builtin/packages/flux-core/package.py
@@ -20,6 +20,12 @@ class FluxCore(AutotoolsPackage):
     license("LGPL-3.0-only")

     version("master", branch="master")
+    version("0.73.0", sha256="d029c3da68bd0a0bea40d964de772e90a55eec72303b610396882f9e94d8c0c6")
+    version("0.72.0", sha256="1642d9f93cca6e0e934b534609787a31753462215ab376d190cdced16c386524")
+    version("0.71.0", sha256="023fd3e2153e20ba28cdf60fefa14d60053df61de3b9e273bf6f9a9ebdef0b52")
+    version("0.70.0", sha256="f68fbc2038d7c0d54c71260b4a8253a73cf6abc09a663ab060a00a4181a9fa94")
+    version("0.69.0", sha256="c44fe9c41e54c2a7dcde24c660c07c8b422072540add0447cbba867719e167b5")
+    version("0.68.0", sha256="fd3d0b0b13136f3914733c7f9e775372a8808d3c7c724ba076fda277a5abeae3")
     version("0.67.0", sha256="9406e776cbeff971881143fd1b94c42ec912e5b226401d2d3d91d766dd81de8c")
     version("0.66.0", sha256="0a25cfb1ebc033c249614eb2350c6fb57b00cdf3c584d0759c787f595c360daa")
     version("0.65.0", sha256="a60bc7ed13b8e6d09e99176123a474aad2d9792fff6eb6fd4da2a00e1d2865ab")
```

**Comment by grondo** [comment]
It should be automated (@vsoch can we turn those back on now?), but sure if you want to catch us up, that would be great! Thank you!

**Comment by vsoch** [comment]
The py-cffi is still failing the flux-core build. I had tested it with all types (build/link/run) removed to use the defaults and the PR that was merged added all three (which I didn't test, but assumed) so something is still off.

![Image](https://github.com/user-attachments/assets/3516fae5-ea6b-4730-93ff-7f604fc2adc9)

**Comment by vsoch** [comment]
It's installed, and at the correct version, so this is likely something to do with the spack environment not exposing it to be found. 

![Image](https://github.com/user-attachments/assets/da70de3e-4bbf-4f0d-9cdf-2cd12f37b639)

I'll try a local build and see if I can reproduce. Spack is... challenging with Python modules. :/

**Comment by grondo** [comment]
Thanks for looking at this @vsoch!

**Comment by vsoch** [comment]
@grondo can you try a quick clone and build? It is failing on my machine for not being able to build cmake, and it isn't adding the one I have installed as an external.  😭 

I just added this to the top of the current package.py:

```python
    version("0.73.0")
```

**Comment by vsoch** [comment]
@grondo as an alternative I can add an option to the spack updater to disable build tests (and do so for flux-core), or I could just do a PR that adds all the missing versions manually.  But that doesn't fix whatever this underlying issue is, and means the potential issues will just propagate to the users (and they will open issues). The challenge with spack is that an issue in CI won't necessarily trigger in some other environment. Let me know your thoughts - that would be a quick solution to clear up the backlog of missing versions, but we'd still need to deal with whatever this bug is.

**Comment by grondo** [comment]
Sorry, @vsoch. I had started to work on this, but now my Internet is down right now for maintenance. I'll try to get back to it this afternoon. Maybe @trws has some advice here. I haven't worked with the spack stuff in quite awhile.

**Comment by vsoch** [comment]
@grondo here are the steps I took (ymmv):

- Clone the current spack
- Add the version above to the flux-core package.py
- bin/spack install `flux-core@0.72.0`

Unfortunately you'll probably hit a million issues with other packages, at least I always do. Probably @trws can better help.

**Comment by grondo** [comment]
I'm not very good with spack, but my build failed here:
```
2 errors found in build log:
     165    2.1.0. You may need to re-run configure, setting the
     166    variables PYTHON_CPPFLAGS, PYTHON_LIBS, PYTHON_SITE_PKG,
     167    PYTHON_EXTRA_LIBS and PYTHON_EXTRA_LDFLAGS by hand.
     168    Moreover, to disable this check, set PYTHON_NOVERSIONCHECK
     169    to something else than an empty string.
     170    
  >> 171    configure: error: in `/tmp/grondo/spack-stage/spack-stage-flux-core
            -0.73.0-nezhozivi5id6nnqsdqe7ipojoaomilh/spack-src/spack-build':
  >> 172    configure: error: Giving up
     173    See `config.log' for more details
```

I saw it build python 3.11 so I'm confused..

**Comment by vsoch** [comment]
@grondo I had old configuration files in my spack home (before the compiler refactor) which I just discovered after gromacs was hanging more than an hour trying to install. Gromacs is running now, so I'll try flux-core again right after that!

**Comment by vsoch** [comment]
OK no luck, it was stuck (probably concretizing) for several hours, and then I control C'd it.

**Comment by grondo** [comment]
I seem to be getting farther than you, but I'm getting stuck in flux-core configure due to the Python linking problem.
The flux-core `package.py` `depends_on` Python, but spack is not setting up the environment so that flux-core's configure can find it.

This seems like it should be a simple problem to me, but I do not know spack well enough to debug it. 🤷 

Maybe I will try starting from scratch.

**Comment by grondo** [comment]
Ok, I think I figured this out. Since #6303 flux-core needs py-setuptools.

When I add
``python
        depends_on("py-setuptools", type=("build"))
```

Then the build succeeds.

**Comment by vsoch** [comment]
That's strange - didn't we add that before?

**Comment by vsoch** [comment]
https://github.com/flux-framework/spack/pull/274

**Comment by grondo** [comment]
Hm, am I on the wrong spack branch? The latest flux-core version in my `package.py` is `0.64.0`, so I must be. 🤦  Or my branch was not updated. Given that is taking about 30 minutes to do a `git reset origin/develop` maybe my previous attempt failed.

Anyway, since that worked I'm confident the current package builds. We should just go ahead and get the version updates into a spack PR.

**Comment by vsoch** [comment]
I already prepared it, will merge soon (and it will run updates).

https://github.com/flux-framework/spack/pull/316

I'll disable the flux-core CI again if it continues to fail. I think in practice people can just easily pip install python-cffi or apt-get / yum install it. Using spack for Python packages is usually erroneous.

**Comment by grondo** [comment]
Thank you!

**Comment by vsoch** [comment]
https://github.com/spack/spack/pull/49893

**Comment by grondo** [comment]
Thanks to @v, @trws and @tgamblin, the issues with the flux-core spack package are resolved! 🎉

**Comment by wihobbs** [comment]
Woohoo! Thanks everyone. Pinging @JaeseungYeom, I know he was asking about this.

**Comment by garlick** [comment]
If there are updated runes for building spack, we should update 

https://flux-framework.readthedocs.io/projects/flux-core/en/latest/guide/build.html#spack

I'm lost in the weeds randomly trying stuff.

**Comment by vsoch** [comment]
I think we can simply just do:

```bash
git clone --depth=1 https://github.com/spack/spack.git
cd spack
. share/spack/setup-env.sh
spack install flux-core
spack load flux-core
```

What runes are you lost in @garlick ?

**Comment by garlick** [comment]
Hmm, that isn't working for me. 
```
 garlick@system76-pc:/tmp$ git clone --depth=1 https://github.com/spack/spack.git
Cloning into 'spack'...
remote: Enumerating objects: 21286, done.
remote: Counting objects: 100% (21286/21286), done.
remote: Compressing objects: 100% (12208/12208), done.
remote: Total 21286 (delta 997), reused 13560 (delta 929), pack-reused 0 (from 0)
Receiving objects: 100% (21286/21286), 14.84 MiB | 18.00 MiB/s, done.
Resolving deltas: 100% (997/997), done.
 garlick@system76-pc:/tmp$ cd spack
 garlick@system76-pc:/tmp/spack$ . share/spack/setup-env.sh
 garlick@system76-pc:/tmp/spack$ spack install flux-core
/tmp/spack/lib/spack/spack/solver/concretize.lp:1459:23-63: info: atom does not occur in any rule head:
  compiler_supports_target(Compiler,#Anon0,#Anon1)

/tmp/spack/lib/spack/spack/solver/concretize.lp:1477:10-61: info: atom does not occur in any rule head:
  compiler_supports_target(Compiler,Version,Target)

==> Error: failed to concretize `flux-core` for the following reasons:
     1. Only external, or concrete, compilers are allowed for the cxx language
     2. Only external, or concrete, compilers are allowed for the c language
```

Adding the specific compiler version doesn't seem to fix the above problems, e.g. I get more of the same
```
$ spack install flux-core %gcc@12.2.0
/tmp/spack/lib/spack/spack/solver/concretize.lp:1459:23-63: info: atom does not occur in any rule head:
  compiler_supports_target(Compiler,#Anon0,#Anon1)

/tmp/spack/lib/spack/spack/solver/concretize.lp:1477:10-61: info: atom does not occur in any rule head:
  compiler_supports_target(Compiler,Version,Target)

==> Error: failed to concretize `flux-core %gcc@12.2.0` for the following reasons:
     1. Only external, or concrete, compilers are allowed for the cxx language
     2. Only external, or concrete, compilers are allowed for the c language
     3. Cannot satisfy 'gcc@12.2.0'
```

Sorry if I'm totally missing something basic!

**Comment by garlick** [comment]
Oh I just realized this is a closed issue.  I'll open a new one for the docs update.  Sorry.
