### ISSUE TITLE
running flux on sierra under LSF/PMIx

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#918]
@trws says:

> I thought this might at least amuse folks.  For reasons of other projects I've
been doing some testing on rzmanta, and after fixing the flux spack package
up, flux builds on rzmanta.  It does not actually bootstrap directly under
LSF, but using a build of mpich's mpiexec.hydra it *does* run quite nicely
under it.  The command to run an interactive flux session on four nodes this
way is basically:

```
#ahead of time: spack install flux mpich ; spack load flux ; spack load mpich
bsub -n 4 -R "span[ptile=1]" -x -G guests -Ip  mpiexec.hydra -np 4 flux broker /bin/bash
```

It still has some issues, the pty doesn't seem to propagate quite right, but
it will run and schedule jobs on little-endian powerpc without slurm.

**Comment by garlick** [comment]
I had thought that we might be able to bootstrap via pmix on that
system;  that is, our PMI client library would find PMIX_SERVER_URI
set in the environment as a hint to dlopen libpmix.so and use PMI-1
backwards compat functions on offer there.  If that didn't work
let's get a bug open on it?

**Comment by garlick** [comment]
@trws says:

> It may be able to work, but does not currently work out of the box.  The
current situation is that PMIX_SERVER_URI is set, libpmix is available, but
not normally in library path, but I've got it added in LD_LIBRRAY_PATH, and
running flux broker under it with multiple nodes results in a hang.  I can try
and track this down a bit if you like while I'm listening to openmp
optimization stuff this afternoon.  The current result of running it with as
much logging as I know how to turn on is the following:

```
[scogland@rzmanta25:~]$ bsub -n 4 -R "span[ptile=1]" -x -G guests -Ip  env
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/ibm/spectrum_mpi/lib/
/opt/ibm/spectrum_mpi/bin/mpirun -np 4 flux -v broker -v -S
log-stderr-level=17 flux kvs dir -r resource
Job <7221> is submitted to default queue <pbatch>.
<<Waiting for dispatch ...>>
<<Starting on rzmanta6>>
FLUX_PMI_LIBRARY_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/lib/flux/libpmi.so
LUA_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/share/lua/5.1/?.lua;/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/lua-5.1.5-lnkdswqbzlt3p65gjcobwxdzzdsf6l6u/lib/lua/5.1/?/init.lua;/usr/workspace/w
srzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/lua-5.1.5-lnkdswqbzlt3p65gjcobwxdzzdsf6l6u/lib/lua/5.1/?.lua;/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/lua-5.1.5-lnkdswqbzlt3p65gjcobwxdzzdsf6l6u/share/lua/5.1/?/init.lua;/usr/workspace/wsrzc/scogland/spack/opt/spa
ck/linux-rhel7-ppc64le/gcc-4.8.5/lua-5.1.5-lnkdswqbzlt3p65gjcobwxdzzdsf6l6u/share/lua/5.1/?.lua;;;
FLUX_EXEC_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/libexec/flux/cmd
FLUX_RC3_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/etc/flux/rc3
FLUX_SEC_DIRECTORY=/g/g12/scogland/.flux
PYTHONPATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/lib/python2.7/site-packages
LUA_CPATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/lib64/lua/5.1/?.so;/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/lua-5.1.5-lnkdswqbzlt3p65gjcobwxdzzdsf6l6u/lib/lua/5.1/?.so;;;
FLUX_CONNECTOR_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/lib/flux/connectors
MANPATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/share/man:/usr/tcetmp/packages/gcc/gcc-4.9.3/share/man:/usr/share/lmod/lmod/share/man:/opt/lsf/10.1/man:/usr/man:/usr/share/man:/usr/local/man:/usr/X11R6/man:/usr/lib64/mvapich/de
fault/man
FLUX_WREXECD_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/libexec/flux/wrexecd
FLUX_WRECK_LUA_PATTERN=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/etc/wreck/lua.d/*.lua
FLUX_MODULE_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/lib/flux/modules
FLUX_RC1_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/etc/flux/rc1
sub-command search path: /usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/libexec/flux/cmd
flux: trying to exec /usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/libexec/flux/cmd/flux-broker
FLUX_PMI_LIBRARY_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/lib/flux/libpmi.so
LUA_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/share/lua/5.1/?.lua;/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/lua-5.1.5-lnkdswqbzlt3p65gjcobwxdzzdsf6l6u/lib/lua/5.1/?/init.lua;/usr/workspace/w
srzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/lua-5.1.5-lnkdswqbzlt3p65gjcobwxdzzdsf6l6u/lib/lua/5.1/?.lua;/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/lua-5.1.5-lnkdswqbzlt3p65gjcobwxdzzdsf6l6u/share/lua/5.1/?/init.lua;/usr/workspace/wsrzc/scogland/spack/opt/spa
ck/linux-rhel7-ppc64le/gcc-4.8.5/lua-5.1.5-lnkdswqbzlt3p65gjcobwxdzzdsf6l6u/share/lua/5.1/?.lua;;;
FLUX_EXEC_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/libexec/flux/cmd
FLUX_RC3_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/etc/flux/rc3
FLUX_SEC_DIRECTORY=/g/g12/scogland/.flux
PYTHONPATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/lib/python2.7/site-packages
LUA_CPATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/lib64/lua/5.1/?.so;/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/lua-5.1.5-lnkdswqbzlt3p65gjcobwxdzzdsf6l6u/lib/lua/5.1/?.so;;;
FLUX_CONNECTOR_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/lib/flux/connectors
MANPATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/share/man:/usr/tcetmp/packages/gcc/gcc-4.9.3/share/man:/usr/share/lmod/lmod/share/man:/opt/lsf/10.1/man:/usr/man:/usr/share/man:/usr/local/man:/usr/X11R6/man:/usr/lib64/mvapich/de
fault/man
FLUX_WREXECD_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/libexec/flux/wrexecd
FLUX_WRECK_LUA_PATTERN=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/etc/wreck/lua.d/*.lua
FLUX_MODULE_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/lib/flux/modules
FLUX_RC1_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/etc/flux/rc1
sub-command search path: /usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/libexec/flux/cmd
flux: trying to exec /usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/libexec/flux/cmd/flux-broker
FLUX_PMI_LIBRARY_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/lib/flux/libpmi.so
LUA_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/share/lua/5.1/?.lua;/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/lua-5.1.5-lnkdswqbzlt3p65gjcobwxdzzdsf6l6u/lib/lua/5.1/?/init.lua;/usr/workspace/w
srzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/lua-5.1.5-lnkdswqbzlt3p65gjcobwxdzzdsf6l6u/lib/lua/5.1/?.lua;/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/lua-5.1.5-lnkdswqbzlt3p65gjcobwxdzzdsf6l6u/share/lua/5.1/?/init.lua;/usr/workspace/wsrzc/scogland/spack/opt/spa
ck/linux-rhel7-ppc64le/gcc-4.8.5/lua-5.1.5-lnkdswqbzlt3p65gjcobwxdzzdsf6l6u/share/lua/5.1/?.lua;;;
FLUX_EXEC_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/libexec/flux/cmd
FLUX_RC3_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/etc/flux/rc3
FLUX_SEC_DIRECTORY=/g/g12/scogland/.flux
PYTHONPATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/lib/python2.7/site-packages
LUA_CPATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/lib64/lua/5.1/?.so;/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/lua-5.1.5-lnkdswqbzlt3p65gjcobwxdzzdsf6l6u/lib/lua/5.1/?.so;;;
FLUX_CONNECTOR_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/lib/flux/connectors
MANPATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/share/man:/usr/tcetmp/packages/gcc/gcc-4.9.3/share/man:/usr/share/lmod/lmod/share/man:/opt/lsf/10.1/man:/usr/man:/usr/share/man:/usr/local/man:/usr/X11R6/man:/usr/lib64/mvapich/de
fault/man
FLUX_WREXECD_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/libexec/flux/wrexecd
FLUX_WRECK_LUA_PATTERN=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/etc/wreck/lua.d/*.lua
FLUX_MODULE_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/lib/flux/modules
FLUX_RC1_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/etc/flux/rc1
sub-command search path: /usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/libexec/flux/cmd
flux: trying to exec /usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/libexec/flux/cmd/flux-broker
FLUX_PMI_LIBRARY_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/lib/flux/libpmi.so
LUA_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/share/lua/5.1/?.lua;/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/lua-5.1.5-lnkdswqbzlt3p65gjcobwxdzzdsf6l6u/lib/lua/5.1/?/init.lua;/usr/workspace/w
srzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/lua-5.1.5-lnkdswqbzlt3p65gjcobwxdzzdsf6l6u/lib/lua/5.1/?.lua;/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/lua-5.1.5-lnkdswqbzlt3p65gjcobwxdzzdsf6l6u/share/lua/5.1/?/init.lua;/usr/workspace/wsrzc/scogland/spack/opt/spa
ck/linux-rhel7-ppc64le/gcc-4.8.5/lua-5.1.5-lnkdswqbzlt3p65gjcobwxdzzdsf6l6u/share/lua/5.1/?.lua;;;
FLUX_EXEC_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/libexec/flux/cmd
FLUX_RC3_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/etc/flux/rc3
FLUX_SEC_DIRECTORY=/g/g12/scogland/.flux
PYTHONPATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/lib/python2.7/site-packages
LUA_CPATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/lib64/lua/5.1/?.so;/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/lua-5.1.5-lnkdswqbzlt3p65gjcobwxdzzdsf6l6u/lib/lua/5.1/?.so;;;
FLUX_CONNECTOR_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/lib/flux/connectors
MANPATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/share/man:/usr/tcetmp/packages/gcc/gcc-4.9.3/share/man:/usr/share/lmod/lmod/share/man:/opt/lsf/10.1/man:/usr/man:/usr/share/man:/usr/local/man:/usr/X11R6/man:/usr/lib64/mvapich/de
fault/man
FLUX_WREXECD_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/libexec/flux/wrexecd
FLUX_WRECK_LUA_PATTERN=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/etc/wreck/lua.d/*.lua
FLUX_MODULE_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/lib/flux/modules
FLUX_RC1_PATH=/usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/etc/flux/rc1
sub-command search path: /usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/libexec/flux/cmd
flux: trying to exec /usr/workspace/wsrzc/scogland/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/flux-master-xiqyvnxpuskr4tuzztocvaed4icepu3l/libexec/flux/cmd/flux-broker

```

**Comment by trws** [comment]
So, a bit more mysterious, flux correctly finds the PMIX_SERVER_URI and loads the libpmix.so library.  Using the pmi debugging gets this before the hang, and this is somehow the last output:

```
PMI_Init: PMIX_SERVER_URI is set, use libpmix.so
pmi_wrap_create: using /opt/ibm/spectrum_mpi/lib/libpmix.so
```

**Comment by garlick** [comment]
If that's the last message, it would tend to indicate that the libpmix `PMI_Init()` call didn't return, since there is a debug message emitted when our internal `PMI_Init()` call returns and all it does in this case is call the wrapped init function.

If you have a flux-core tree handy, there's a stripped down PMI client that uses the same internal PMI client library as the broker and thus might be a little easier to debug if it hangs too:
```bash
# substitute bsub or whatever for wreckrun:
$ flux wreckrun -N8 src/common/libpmi/test_kvstest
0: put phase: 8.194 sec
0: get phase: 2.526 sec
$
```

**Comment by garlick** [comment]
(by the way the sec units are wrong - should be msec)

**Comment by trws** [comment]
That doesn't hang, it shows init failing:

```
[scogland@rzmanta25:flux-core-config-test]$ bsub -n 8 -R "span[ptile=1]" -x -G guests -Ip  env FLUX_PMI_DEBUG=17 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/ibm/spectrum_mpi/lib/ /opt/ibm/spectrum_mpi/bin/mpirun -np 8 src/common/libpmi/test_kvstest
Job <7249> is submitted to default queue <pbatch>.
<<Waiting for dispatch ...>>
<<Starting on rzmanta13>>
PMI_Init: PMIX_SERVER_URI is set, use libpmix.so
PMI_Init: PMIX_SERVER_URI is set, use libpmix.so
PMI_Init: PMIX_SERVER_URI is set, use libpmix.so
PMI_Init: PMIX_SERVER_URI is set, use libpmix.so
PMI_Init: PMIX_SERVER_URI is set, use libpmix.so
PMI_Init: PMIX_SERVER_URI is set, use libpmix.so
PMI_Init: PMIX_SERVER_URI is set, use libpmix.so
PMI_Init: PMIX_SERVER_URI is set, use libpmix.so
pmi_wrap_create: /opt/ibm/spectrum_mpi/lib/libpmix.so: undefined symbol: hwloc_topology_dup
pmi_wrap_create: /opt/ibm/spectrum_mpi/lib//libpmix.so: undefined symbol: hwloc_topology_dup
-1: PMI_Init rc=-1 operation failed
test_kvstest: PMI_Init: operation failed
pmi_wrap_create: /opt/ibm/spectrum_mpi/lib/libpmix.so: undefined symbol: hwloc_topology_dup
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[26705,1],7]
  Exit code:    1
--------------------------------------------------------------------------
```

With the hwloc library pre-loaded inside of the mpirun (outside of it doesn't work... no clue why) it passes that and gets to the hang:
```
[scogland@rzmanta25:flux-core-config-test]$ bsub -n 8 -R "span[ptile=1]" -x -G guests -Ip  env FLUX_PMI_DEBUG=17 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/ibm/spectrum_mpi/lib/ /opt/ibm/spectrum_mpi/bin/mpirun -np 8 src/common/libpmi/test_kvstest
Job <7249> is submitted to default queue <pbatch>.
<<Waiting for dispatch ...>>
<<Starting on rzmanta13>>
PMI_Init: PMIX_SERVER_URI is set, use libpmix.so
PMI_Init: PMIX_SERVER_URI is set, use libpmix.so
PMI_Init: PMIX_SERVER_URI is set, use libpmix.so
PMI_Init: PMIX_SERVER_URI is set, use libpmix.so
PMI_Init: PMIX_SERVER_URI is set, use libpmix.so
PMI_Init: PMIX_SERVER_URI is set, use libpmix.so
PMI_Init: PMIX_SERVER_URI is set, use libpmix.so
PMI_Init: PMIX_SERVER_URI is set, use libpmix.so
pmi_wrap_create: /opt/ibm/spectrum_mpi/lib/libpmix.so: undefined symbol: hwloc_topology_dup
pmi_wrap_create: /opt/ibm/spectrum_mpi/lib//libpmix.so: undefined symbol: hwloc_topology_dup
-1: PMI_Init rc=-1 operation failed
test_kvstest: PMI_Init: operation failed
pmi_wrap_create: /opt/ibm/spectrum_mpi/lib/libpmix.so: undefined symbol: hwloc_topology_dup
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[26705,1],7]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by garlick** [comment]
Just wanted to note that the following appears on @dongahn's ECP roadmap (poster) for year 1:

> Port/release all of the Flux components to CORAL systems as a user-level tool

Sierra being a [CORAL](https://asc.llnl.gov/coral-info) system -  which is to say we've made a commitment to getting these issues solved.

**Comment by dongahn** [comment]
Thanks for pointing this out @garlick!

**Comment by garlick** [comment]
While attempting to build flux-core 0.7.0 through koji, I ran into the following error prepping the mock environment:

```
INFO: mock.py version 1.2.21 starting (python version = 2.7.5)...
Start: init plugins
INFO: selinux enabled
Finish: init plugins
Start: run
Start: clean chroot
Finish: clean chroot
Start: chroot init
INFO: calling preinit hooks
Mock Version: 1.2.21
INFO: Mock Version: 1.2.21
Start: yum install
Finish: yum install
Finish: chroot init
INFO: Installed packages:
Finish: run
INFO: mock.py version 1.2.21 starting (python version = 2.7.5)...
Start: init plugins
INFO: selinux enabled
Finish: init plugins
Start: run
INFO: Start(/tmp/koji/tasks/9397/39397/local/work/tasks/9395/39395/flux-core-0.7.0-1.ch6.src.rpm)  Config(ch6-chaotic-build-9456-8895)
Start: chroot init
INFO: calling preinit hooks
Mock Version: 1.2.21
INFO: Mock Version: 1.2.21
Finish: chroot init
Start: build phase for flux-core-0.7.0-1.ch6.src.rpm
Start: build setup for flux-core-0.7.0-1.ch6.src.rpm
ERROR: Exception(/tmp/koji/tasks/9397/39397/local/work/tasks/9395/39395/flux-core-0.7.0-1.ch6.src.rpm) Config(ch6-chaotic-build-9456-8895) 0 minutes 2 seconds
INFO: Results and/or logs in: /var/lib/mock/ch6-chaotic-build-9456-8895/result
ERROR: Command failed: 
 # /usr/bin/yum-builddep --installroot /var/lib/mock/ch6-chaotic-build-9456-8895/root/ /var/lib/mock/ch6-chaotic-build-9456-8895/root//builddir/build/SRPMS/flux-core-0.7.0-1.ch6.src.rpm --setopt=tsflags=nocontexts
Getting requirements for flux-core-0.7.0-1.ch6.src
 --> zeromq-devel-4.1.5-2.ch6.ppc64le
 --> czmq-devel-3.0.2-2.ch6.ppc64le
 --> jansson-devel-2.6-4.ch6.ppc64le
 --> hwloc-devel-1.11.2-1.el7.ppc64le
 --> sqlite-devel-3.7.17-8.el7.ppc64le
 --> lua-devel-5.1.4-15.el7.ppc64le
 --> munge-devel-0.5.12-1.ch6.ppc64le
 --> lua-posix-32-2.el7.ppc64le
 --> asciidoc-8.6.8-5.el7.noarch
 --> 12:aspell-0.60.6.1-9.el7.ppc64le
 --> net-tools-2.0-0.17.20131004git.el7.ppc64le
 --> python-devel-2.7.5-48.el7.ppc64le
 --> python-cffi-1.5.0-2.ch6.ppc64le
 --> python-pycparser-2.10-1.el7.noarch
 --> python-ply-3.4-4.el7.noarch
 --> libsodium-devel-1.0.5-1.el7.ppc64le
 --> openpgm-devel-5.2.122-2.el7.ppc64le
 --> krb5-devel-1.14.1-27.1chaos.ch6.ppc64le
Error: Package: hwloc-libs-1.11.2-1.el7.ppc64le (build)
           Requires: libltdl.so.7()(64bit)
Error: Package: graphviz-2.30.1-19.el7.ppc64le (build)
           Requires: libltdl.so.7()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```
Not sure what this is all about yet...

**Comment by grondo** [comment]
I did a scratch build of flux-core 0.7.0-2 and the issue with hwloc packaging seems to have been resolved. However, now the build fails on ppc64le during `./configure` with `C compiler cannot create executables`.

The problem seems to be that gcc on the ppc64le doesn't like the `-mtune=generic` option:

```
gcc: error: unrecognized argument in option '-mtune=generic'
gcc: note: valid arguments to '-mtune=' are: 401 403 405 405fp 440 440fp 464 464fp 476 476fp 505 601 602 603 603e 604 604e 620 630 740 7400 7450 750 801 821 823 8540 8548 860 970 G3 G4 G5 a2 cell e300c2 e300c3 e500mc e500mc64 e5500 e6500 ec603e native power3 power4 power5 power5+ power6 power6x power7 power8 powerpc powerpc64 powerpc64le rs64 titan
```

This option is manually added in `flux-core.spec` here:
```
KOJI_CFLAGS="-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic"
CFLAGS="${KOJI_CFLAGS} -Wno-error=strict-aliasing"
```

I haven't looked into this yet, but wondering if someone known why these options were manually added to the koji build? Can I just get rid of them, or do we need a ifarch section for pcc64le here?

**Comment by garlick** [comment]
I'm guessing that was probably me, but I cannot for the life of me remember doing it or why.  Does the koji git repo's commit log say anything?

**Comment by grondo** [comment]
```
commit fad2b0acfb9fc3b38685c34a8041f9551878ac1d
Author: Jim Garlick <garlick.jim@gmail.com>
Date:   Thu Jan 28 11:15:59 2016 -0800

    restore koji CFLAGS, disable hanging make check

```

**Comment by grondo** [comment]
It does seem like make check is still hanging in the build. hrm...

**Comment by garlick** [comment]
Sorry, I still don't remember why the  `KOJI_CFLAGS` needed setting....

**Comment by grondo** [comment]
I did verify that without `-m` options in CFLAGS, and with `make check` disabled, the flux-core package appears to build on ppc6le now.

I just conditionally set flags like this for now:

```diff

diff --git a/flux-core.spec b/flux-core.spec
index aa8d728..1bf8051 100644
--- a/flux-core.spec
+++ b/flux-core.spec
@@ -51,8 +51,10 @@ various distributed services.
 %setup -n %{name}-%{version}
 
 %build
-KOJI_CFLAGS="-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-pr
-CFLAGS="${KOJI_CFLAGS} -Wno-error=strict-aliasing"
+%ifnarch ppc64le
+KOJI_FLAGS="-m64 -mtune=generic"
+%endif
+CFLAGS="${KOJI_CFLAGS} -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions 
 
 %configure \
        --disable-static \
```

**Comment by grondo** [comment]
As a datapoint, flux-core-0.8.0 RPMs built fine in our local koji build farm.
However, I'm not sure if the package will work once it gets installed on a ppc64le system, so I'll leave this issue open still.

**Comment by garlick** [comment]
Note that #1555 worked through some issues wtih running flux under jsrun:
* libpmix.so no longer provides PMI_ (v1) symbols
* upstream pmix moved those symbols to libpmi.so, but spectrum MPI doesn't provide libpmi.so.
* PMIX_SERVER_URI (checked in flux PMI client code) is deprecated in favor of PMIX_SERVER_URI2

@dongahn was able to build the pmi1.c code from the pmix project as a standalone library.  The PMI_LIBRARY environment var can be used to direct Flux to use that library.

We'll want to update the PMIX heuristic in `src/common/libpmi/pmi.c` to reflect these changes.   We could simply delete the PMIX leg of that conditional and expect libpmi.so to be found using the other logic there.

Or (for extra credit), we could check for one or the other of the PMIX_SERVER_URI variables, and if found, add code to dlopen libpmix.so and map our PMI-1 internal API to pmix calls following the pattern in pmi1.c from the pmix project.  Then the missing libpmi.so on sierra won't have to be worked around.

**Comment by dongahn** [comment]
> We'll want to update the PMIX heuristic in src/common/libpmi/pmi.c to reflect these changes. We could simply delete the PMIX leg of that conditional and expect libpmi.so to be found using the other logic there.

My recommendation is to remove the PMIX heuristics as libpmix no longer has PMI libraries.

**Comment by garlick** [comment]
OK, I'll submit a quick PR for this today.
